// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/neda1985/getir/model"

// InMemoryManager is an autogenerated mock type for the InMemoryManager type
type InMemoryManager struct {
	mock.Mock
}

// Fetch provides a mock function with given fields: key
func (_m *InMemoryManager) Fetch(key string) (string, error) {
	ret := _m.Called(key)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: input
func (_m *InMemoryManager) Insert(input model.InMemoryDataIO) error {
	ret := _m.Called(input)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.InMemoryDataIO) error); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
