// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/neda1985/getir/model"

// MongoManager is an autogenerated mock type for the MongoManager type
type MongoManager struct {
	mock.Mock
}

// FetchResponse provides a mock function with given fields: _a0
func (_m *MongoManager) FetchResponse(_a0 model.FetchRequest) (model.FetchResponse, error) {
	ret := _m.Called(_a0)

	var r0 model.FetchResponse
	if rf, ok := ret.Get(0).(func(model.FetchRequest) model.FetchResponse); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(model.FetchResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.FetchRequest) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
